services:
  my_web:
    container_name: my_web
    image: nginx:1.27.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist/camera/browser:/usr/share/nginx/html
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    restart: always
networks:
  my_network:
    driver: bridge